INSERT INTO Users (name, email) VALUES
('Emily Chen', 'emily@goalstack.dev'),
('James Rodriguez', 'james@goalstack.dev'),
('Amina Yusuf', 'amina@goalstack.dev'),
('Carlos Mendes', 'carlos@goalstack.dev'),
('Sarah Khan', 'sarah@goalstack.dev'),
('Noah Lee', 'noah@goalstack.dev'),
('Maya Patel', 'maya@goalstack.dev'),
('David Kim', 'david@goalstack.dev'),
('Fatima Said', 'fatima@goalstack.dev'),
('Luca Romano', 'luca@goalstack.dev');


INSERT INTO Goals (user_id, goal_title) VALUES
(1, 'Master SQL'),
(1, 'Git & GitHub Workflows'),
(2, 'React Basics'),
(2, 'Next.js Exploration'),
(3, 'Advanced Python'),
(3, 'Learn Flask'),
(4, 'Build Portfolio Website'),
(4, 'CSS Grid & Flexbox'),
(5, 'Pandas & DataFrames'),
(5, 'Data Cleaning with Python'),
(6, 'Intro to Linux CLI'),
(6, 'Learn Bash Scripting'),
(7, 'Cloud Fundamentals'),
(7, 'AWS Deployment'),
(8, 'Frontend with Tailwind'),
(8, 'React Hooks'),
(9, 'JavaScript Patterns'),
(9, 'DOM Manipulation'),
(10, 'Algorithms Bootcamp'),
(10, 'Big O Analysis'),
(10, 'System Design Basics');

INSERT INTO Tasks (goal_id, task_title, status, priority) VALUES
(1, 'SELECT statements', 'done', 2),
(1, 'JOINs practice', 'in progress', 1),
(2, 'Init repo and push', 'pending', 3),
(2, 'Branching & merging', 'done', 2),
(3, 'JSX & Components', 'in progress', 2),
(3, 'React Router', 'pending', 3),
(4, 'Pages in Next.js', 'done', 2),
(4, 'API routes', 'pending', 2),
(5, 'Decorators in Python', 'in progress', 2),
(5, 'List comprehensions', 'done', 1),
(6, 'Create REST API', 'pending', 2),
(6, 'User authentication', 'in progress', 1),
(7, 'Setup HTML/CSS', 'done', 3),
(7, 'Mobile Responsive Layout', 'in progress', 2),
(8, 'Grid templates', 'pending', 3),
(8, 'Flexbox containers', 'done', 2),
(9, 'Read CSVs with Pandas', 'done', 2),
(9, 'Data types cleanup', 'done', 1),
(10, 'Drop missing values', 'in progress', 2),
(10, 'Impute columns', 'pending', 3),
(11, 'List files in dir', 'done', 1),
(11, 'Use pipes & grep', 'pending', 2),
(12, 'Make bash script', 'in progress', 1),
(12, 'Crontab scheduling', 'pending', 2),
(13, 'Cloud terms & IaaS', 'done', 3),
(13, 'Virtual machines intro', 'in progress', 2),
(14, 'Deploy on EC2', 'done', 1),
(14, 'Setup RDS DB', 'pending', 2),
(15, 'Build Tailwind page', 'done', 2),
(15, 'Use Tailwind components', 'in progress', 1),
(16, 'useState / useEffect', 'pending', 3),
(16, 'Custom Hooks', 'done', 2),
(17, 'Module pattern', 'in progress', 2),
(17, 'Factory functions', 'done', 1),
(18, 'Query selectors', 'done', 1),
(18, 'Event delegation', 'pending', 2),
(19, 'Binary Search', 'in progress', 1),
(20, 'Big-O cheat sheet', 'done', 2),
(21, 'System Design reading', 'pending', 3);


INSERT INTO Progress_logs (task_id, time_spent) VALUES
(1, 30), (1, 25),
(2, 40),
(4, 20),
(5, 50), (5, 35),
(6, 10),
(9, 25), (9, 30),
(10, 20),
(11, 45),
(13, 60),
(15, 15),
(16, 35),
(17, 30), (17, 10),
(18, 40),
(19, 20),
(20, 45),
(28, 25), (28, 15),
(30, 20),
(34, 50),
(36, 35);
